app = "yale-events"
primary_region = "iad"

[mounts]
  source = "yev_data"
  destination = "/app/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"  # the scrape loop runs in this machine
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    method = "GET"
    path = "/events?limit=1"
    interval = "30s"
    timeout = "5s"
    grace_period = "20s"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
